// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].put').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/index.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/refresh': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/refresh.post').default>>>>
    }
    '/api/finance/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance/[id].put').default>>>>
    }
    '/api/finance/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance/import.post').default>>>>
    }
    '/api/finance': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance/index.post').default>>>>
    }
    '/api/finance/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance/summary.get').default>>>>
    }
    '/api/orders/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id].put').default>>>>
    }
    '/api/orders/by-number': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/by-number.get').default>>>>
    }
    '/api/orders/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/import.post').default>>>>
    }
    '/api/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.post').default>>>>
    }
    '/api/orders/sku-search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/sku-search.get').default>>>>
    }
    '/api/products/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].put').default>>>>
    }
    '/api/products/hpp-export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/hpp-export.get').default>>>>
    }
    '/api/products/hpp-import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/hpp-import.post').default>>>>
    }
    '/api/products/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/import.post').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.post').default>>>>
    }
    '/api/shopee-ads/group': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shopee-ads/group.get').default>>>>
    }
    '/api/shopee-ads/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shopee-ads/import.post').default>>>>
    }
    '/api/shopee-ads': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shopee-ads/index.get').default>>>>
    }
    '/api/shopee-ads/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shopee-ads/summary.get').default>>>>
    }
    '/api/stores/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stores/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stores/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stores/[id].put').default>>>>
    }
    '/api/stores': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stores/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stores/index.post').default>>>>
    }
    '/api/tiktok-ads/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tiktok-ads/[id].delete').default>>>>
    }
    '/api/tiktok-ads/group': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tiktok-ads/group.get').default>>>>
    }
    '/api/tiktok-ads/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tiktok-ads/import.post').default>>>>
    }
    '/api/tiktok-ads': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tiktok-ads/index.get').default>>>>
    }
    '/api/tiktok-ads/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tiktok-ads/summary.get').default>>>>
    }
    '/api/user/password': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/password.put').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}