// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/3/2026, 9:16:04 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/macbookpro/Documents/1.Saas/REKAPA/rekapnuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/1.Saas/REKAPA/rekapnuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/1.Saas/REKAPA/rekapnuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/1.Saas/REKAPA/rekapnuxt/plugins/**/*.{js,ts,mjs}","/Users/macbookpro/Documents/1.Saas/REKAPA/rekapnuxt/composables/**/*.{js,ts,mjs}","/Users/macbookpro/Documents/1.Saas/REKAPA/rekapnuxt/utils/**/*.{js,ts,mjs}","/Users/macbookpro/Documents/1.Saas/REKAPA/rekapnuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/1.Saas/REKAPA/rekapnuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/1.Saas/REKAPA/rekapnuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/1.Saas/REKAPA/rekapnuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;